services:
    app:
        build:
            context: .
            args:
                APP_ENV: ${APP_ENV}
        environment:
            APP_ENV: ${APP_ENV}
            CONTAINER_ROLE: app
        container_name: blog_app
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    mysql:
        image: mysql:8
        container_name: blog_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
        #   MYSQL_USER: ${DB_USERNAME}
        #   MYSQL_PASSWORD: ${DB_PASSWORD}
        # ports:
        #   - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    vite:
        image: node:20-alpine
        container_name: blog_vite
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "5173:5173" # Vite default port
        command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
        environment:
            VITE_APP_NAME: "Blog"

volumes:
    db_data:
